import "./globals.css";
import { Inter } from "next/font/google";
import NavMenu from "./NavMenu";
import About from "../about/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <NavMenu />
            <body className={inter.className}>{children}</body>
        </html>
    );
}
